// <auto-generated />
using CRUDTask.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRUDTask.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260811045821_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRUDTask.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Samsung flagship smartphone with excellent performance and camera.",
                            Name = "Samsung Galaxy S24",
                            Price = 799.99m,
                            Rate = 4.7000000000000002
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apple smartphone with A16 Bionic chip and advanced camera system.",
                            Name = "iPhone 15",
                            Price = 699.99m,
                            Rate = 4.7999999999999998
                        },
                        new
                        {
                            Id = 3,
                            Description = "Google smartphone with an excellent camera and clean Android experience.",
                            Name = "Google Pixel 8",
                            Price = 599.99m,
                            Rate = 4.5999999999999996
                        },
                        new
                        {
                            Id = 4,
                            Description = "Powerful Xiaomi smartphone with a high-quality AMOLED display.",
                            Name = "Xiaomi 14",
                            Price = 649.99m,
                            Rate = 4.5
                        },
                        new
                        {
                            Id = 5,
                            Description = "Fast Android smartphone with a powerful processor and large battery.",
                            Name = "OnePlus 12",
                            Price = 749.99m,
                            Rate = 4.5999999999999996
                        },
                        new
                        {
                            Id = 6,
                            Description = "Mid-range Samsung smartphone with a great display and long battery life.",
                            Name = "Samsung Galaxy A55",
                            Price = 449.99m,
                            Rate = 4.4000000000000004
                        },
                        new
                        {
                            Id = 7,
                            Description = "Reliable Apple smartphone with a powerful processor and great camera.",
                            Name = "iPhone 14",
                            Price = 599.99m,
                            Rate = 4.7000000000000002
                        },
                        new
                        {
                            Id = 8,
                            Description = "Affordable smartphone with AMOLED display and strong battery performance.",
                            Name = "Xiaomi Redmi Note 13",
                            Price = 299.99m,
                            Rate = 4.2999999999999998
                        },
                        new
                        {
                            Id = 9,
                            Description = "Modern Android smartphone with a unique design and smooth performance.",
                            Name = "Nothing Phone 2",
                            Price = 549.99m,
                            Rate = 4.4000000000000004
                        },
                        new
                        {
                            Id = 10,
                            Description = "Affordable performance-focused smartphone with a premium design.",
                            Name = "OnePlus Nord 4",
                            Price = 399.99m,
                            Rate = 4.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
